### ISSUE TITLE
Getting this error when looking to install

### ISSUE THREAD

**Issue by mediajolt001** [keijiro/VfxGraphAssets#1]
![Screen Shot 2021-02-24 at 2 40 14 PM](https://user-images.githubusercontent.com/11758783/109063115-67099380-76ae-11eb-98f6-ddea5c0edcb2.png)

It looks like it's looking for a version of ShaderGraph that isn't available?

**Comment by nejurgis** [comment]
Same here, it's using shadergraph@11.0.0 which is not yet published, or i don't know how to access, same with the HDRP:

```
 Project has invalid dependencies:
    com.unity.render-pipelines.high-definition: Package [com.unity.render-pipelines.high-definition@11.0.0] cannot be found
    com.unity.shadergraph: Package [com.unity.shadergraph@11.0.0] cannot be found
```

**Comment by keijiro** [comment]
I forgot to mention but it requires Unity 2021.1 beta.

**Comment by keijiro** [comment]
Added to the doc.

https://github.com/keijiro/VfxGraphAssets/commit/876a92ce17580935a20e31d1b53f7468ae33826a

**Comment by keijiro** [comment]
I'm closing this issue as resolved. Please feel free to reopen it for further problems.

**Comment by keijiro** [comment]
FYI: I downgraded the package to Unity 2020.2. Now it supports HDRP 10.x.
